import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// ============================================
// 构建后自动部署到目标目录（可选功能）
// 如需启用，取消下面一行的注释：
// const AUTO_DEPLOY = true;
// ============================================
const AUTO_DEPLOY = false;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
});

// 部署函数
function deploy() {
	if (!AUTO_DEPLOY) return;
	
	try {
		console.log('\n[esbuild] 正在部署到 obsidian-auto-plus...');
		execSync('node scripts/deploy.js', { stdio: 'inherit' });
	} catch (error) {
		console.error('[esbuild] 部署失败:', error.message);
	}
}

if (prod) {
	await context.rebuild();
	deploy();
	process.exit(0);
} else {
	await context.watch();
	// 开发模式下每次构建完成后也触发部署
	if (AUTO_DEPLOY) {
		context.on('end', deploy);
	}
}
